services:
  chatpdf:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatpdf-app
    container_name: chatpdf-app
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
