services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434

  chatpdf:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatpdf-app
    container_name: chatpdf-app
    ports:
      - 8501:8501
